package com.cognizant.medlab.domain.patient;

import com.cognizant.medlab.domain.common.BaseEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;

import java.time.LocalDate;

/**
 * Patient — core KYC entity.
 *
 * MRN (Medical Record Number) is auto-generated by PatientService and is
 * the stable external identifier (e.g. "MRN-000042").
 */
@Entity
@Table(name = "patients")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
@EqualsAndHashCode(callSuper = false, of = "medicalRecordNumber")
public class Patient extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "mrn", unique = true, nullable = false, length = 50)
    private String medicalRecordNumber;

    @NotBlank
    @Column(name = "full_name", nullable = false, length = 150)
    private String fullName;

    @Past
    @Column(name = "dob")
    private LocalDate dob;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private Gender gender;

    @Email
    @Column(unique = true, length = 100)
    private String email;

    @Column(name = "mobile_number", unique = true, length = 15)
    private String mobileNumber;

    @Column(length = 300)
    private String address;

    @Column(name = "blood_group", length = 10)
    private String bloodGroup;

    @Column(columnDefinition = "TEXT")
    private String allergies;

    @Column(name = "medical_history", columnDefinition = "TEXT")
    private String medicalHistory;

    @Column(name = "consent_given", nullable = false)
    @Builder.Default
    private boolean consentGiven = false;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private PatientStatus status = PatientStatus.ACTIVE;

    // ── Enums ────────────────────────────────────────────────────

    public enum Gender { M, F, O }

    public enum PatientStatus { ACTIVE, INACTIVE, DISCHARGED }
}
